# -*- coding: utf-8 -*-
"""Untitled100.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtm6DBW_5Ljzn3aisG2vTPUxIjqAbMY-
"""

import re

#Define the alias map
SKILL_ALIASES = {
    # Languages
    "python": "python",
    "pyhton": "python",
    "java": "java",
    "javascript": "javascript",
    "javascrpit": "javascript",
    "js": "javascript",
    "typescript": "typescript",
    "typescrpit": "typescript",
    "c++": "cpp",
    "cpp": "cpp",
    "r": "r",
    "kotlin": "kotlin",
    # ML / Data
    "machinelearning": "machine_learning",
    "machine learning": "machine_learning",
    "ml": "machine_learning",
    "sklearn": "machine_learning",
    "deeplearning": "deep_learning",
    "deep learning": "deep_learning",
    "deep-learning": "deep_learning",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "keras": "keras",
    "nlp": "nlp",
    "bert": "bert",
    "xgboost": "xgboost",
    "feature engineering": "feature_engineering",
    "statistics": "statistics",
    "stats": "statistics",
    "regression": "regression",
    "clustering": "clustering",
    "data-viz": "data_visualization",
    "data visualization": "data_visualization",
    "data viz": "data_visualization",
    "matplotlib": "data_visualization",
    "tableau": "data_visualization",
    "power-bi": "data_visualization",
    "power bi": "data_visualization",
    "powerbi": "data_visualization",
    "pandas": "pandas",
    "numpy": "numpy",
    # Web — Frontend
    "react": "react",
    "reacts": "react",
    "reactjs": "react",
    "vue": "vue",
    "vue.js": "vue",
    "vuejs": "vue",
    "redux": "redux",
    "tailwind": "tailwind",
    "html/css": "html_css",
    "html css": "html_css",
    "html": "html_css",
    "css": "html_css",
    "jest": "jest",
    "graphql": "graphql",
    # Web — Backend
    "node.js": "nodejs",
    "nodejs": "nodejs",
    "node js": "nodejs",
    "flask": "flask",
    "spring boot": "spring_boot",
    "springboot": "spring_boot",
    "rest api": "rest_api",
    "rest": "rest_api",
    "restapi": "rest_api",
    "microservices": "microservices",
    # Databases
    "sql": "sql",
    "mysql": "mysql",
    "mysq": "mysql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "mongodb": "mongodb",
    "redis": "redis",
    # DevOps / Cloud
    "docker": "docker",
    "kubernetes": "kubernetes",
    "kubernates": "kubernetes",
    "k8s": "kubernetes",
    "ci/cd": "ci_cd",
    "cicd": "ci_cd",
    "ci cd": "ci_cd",
    "aws": "aws",
    # Mobile
    "android": "android",
    "firebase": "firebase",
    # CS Fundamentals
    "algorithms": "algorithms",
    "algoritms": "algorithms",
    "data structure": "data_structures",
    "data structures": "data_structures",
    "competitive programming": "competitive_programming",
    # Design
    "ui/ux": "ui_ux",
    "ui ux": "ui_ux",
    "figma": "figma"
}

def normalize_skills(skills):
    skills = skills.lower()
    skills = re.split(r'[,
\s]+', skills)
    normalized_skills = []
    for skill in skills:
        if skill in SKILL_ALIASES:
            normalized_skills.append(SKILL_ALIASES[skill])
        else:
            normalized_skills.append(skill)
    return normalized_skills

#Example usage
resume_skills = "Pyhton, MachineLearning, SQL, pandas, numpy, Deep-learning"
normalized_skills = normalize_skills(resume_skills)
print(normalized_skills)

import csv
import math
import sys

#Define the skill aliases
SKILL_ALIASES = {
    "python": "python",
    "pyhton": "python",
    "java": "java",
    "javascript": "javascript",
    "javascrpit": "javascript",
    "js": "javascript",
    "typescript": "typescript",
    "typescrpit": "typescript",
    "c++": "cpp",
    "cpp": "cpp",
    "r": "r",
    "kotlin": "kotlin",

    "machinelearning": "machine_learning",
    "machine learning": "machine_learning",
    "ml": "machine_learning",
    "sklearn": "machine_learning",
    "deeplearning": "deep_learning",
    "deep learning": "deep_learning",
    "deep-learning": "deep_learning",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "keras": "keras",
    "nlp": "nlp",
    "bert": "bert",
    "xgboost": "xgboost",
    "feature engineering": "feature_engineering",
    "statistics": "statistics",
    "stats": "statistics",
    "regression": "regression",
    "clustering": "clustering",
    "data-viz": "data_visualization",
    "data visualization": "data_visualization",
    "data viz": "data_visualization",
    "matplotlib": "data_visualization",
    "tableau": "data_visualization",
    "power-bi": "data_visualization",
    "power bi": "data_visualization",
    "powerbi": "data_visualization",
    "pandas": "pandas",
    "numpy": "numpy",

    "react": "react",
    "reacts": "react",
    "reactjs": "react",
    "vue": "vue",
    "vue.js": "vue",
    "vuejs": "vue",
    "redux": "redux",
    "tailwind": "tailwind",
    "html/css": "html_css",
    "html css": "html_css",
    "html": "html_css",
    "css": "html_css",
    "jest": "jest",
    "graphql": "graphql",

    "node.js": "nodejs",
    "nodejs": "nodejs",
    "node js": "nodejs",
    "flask": "flask",
    "spring boot": "spring_boot",
    "springboot": "spring_boot",
    "rest api": "rest_api",
    "rest": "rest_api",
    "restapi": "rest_api",
    "microservices": "microservices",

    "sql": "sql",
    "mysql": "mysql",
    "mysq": "mysql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "mongodb": "mongodb",
    "redis": "redis",

    "docker": "docker",
    "kubernetes": "kubernetes",
    "kubernates": "kubernetes",
    "k8s": "kubernetes",
    "ci/cd": "ci_cd",
    "cicd": "ci_cd",
    "ci cd": "ci_cd",
    "aws": "aws",

    "android": "android",
    "firebase": "firebase",

    "algorithms": "algorithms",
    "algoritms": "algorithms",
    "data structure": "data_structures",
    "data structures": "data_structures",
    "competitive programming": "competitive_programming",
}

#Function to normalize skills
def normalize_skills(skills_string):
    if not skills_string:
        return []
    normalized = []
    for token in skills_string.split(','):
        token = token.strip().lower()
        if token in SKILL_ALIASES:
            canonical_skill = SKILL_ALIASES[token]
            normalized.append(canonical_skill)
        else:
            # Keep original skill if not found in aliases, but convert to lowercase
            normalized.append(token)

    # Deduplicate while preserving order
    deduplicated = []
    seen = set()
    for skill in normalized:
        if skill not in seen:
            deduplicated.append(skill)
            seen.add(skill)
    return deduplicated

#Function to read CSV file
def read_csv_file(file_name):
    try:
        with open(file_name, 'r') as file:
            reader = csv.DictReader(file)
            data = [row for row in reader]
            return data
    except FileNotFoundError:
        print(f"File {file_name} not found.")
        return []
    except Exception as e:
        print(f"Error reading file {file_name}: {e}")
        return []

#Function to build vocabulary
def build_vocabulary(normalized_skills_map):
    vocabulary = set()
    for skills_list in normalized_skills_map.values():
        vocabulary.update(skills_list)
    return sorted(list(vocabulary))

#Function to compute document frequency
def compute_document_frequency(vocabulary, normalized_skills_map):
    document_frequency = {skill: 0 for skill in vocabulary}
    for skills_list in normalized_skills_map.values():
        for skill in vocabulary:
            if skill in skills_list:
                document_frequency[skill] += 1
    return document_frequency

#Function to compute IDF
def compute_idf(document_frequency, num_documents):
    idf = {}
    for skill, freq in document_frequency.items():
        if freq > 0:
            idf[skill] = math.log(num_documents / freq)
        else:
            idf[skill] = 0.0 # Should ideally not happen if vocabulary is built correctly
    return idf

#Function to build TF-IDF vectors for candidates (TF = 1 / total_unique_skills_in_resume)
def build_candidate_tfidf_vectors(normalized_candidate_skills_map, vocabulary, idf):
    tfidf_vectors = {}
    for candidate_id, skills_normalized in normalized_candidate_skills_map.items():
        tfidf_vector = {}
        if not skills_normalized:
            for skill_in_vocab in vocabulary:
                tfidf_vector[skill_in_vocab] = 0.0
            tfidf_vectors[candidate_id] = tfidf_vector
            continue

        total_unique_skills_in_resume = len(skills_normalized) # normalize_skills already deduplicates

        for skill_in_vocab in vocabulary:
            if skill_in_vocab in skills_normalized:
                tf = 1 / total_unique_skills_in_resume
                tfidf_vector[skill_in_vocab] = tf * idf.get(skill_in_vocab, 0.0)
            else:
                tfidf_vector[skill_in_vocab] = 0.0
        tfidf_vectors[candidate_id] = tfidf_vector
    return tfidf_vectors

#Function to build JD binary vector
def build_jd_binary_vector(vocabulary, job_normalized_skills):
    jd_vector = {}
    for skill_in_vocab in vocabulary:
        if skill_in_vocab in job_normalized_skills:
            jd_vector[skill_in_vocab] = 1
        else:
            jd_vector[skill_in_vocab] = 0
    return jd_vector

#Function to compute cosine similarity
def cosine_similarity(vector1, vector2):
    if not vector1 or not vector2: # Handles cases where a vector might be empty
        return 0.0

    # Ensure both vectors have the same keys and order for dot product if needed
    # Convert dicts to lists based on a common set of keys (e.g., vocabulary)
    common_skills = sorted(list(set(vector1.keys()) | set(vector2.keys())))

    list_vec1 = [vector1.get(skill, 0.0) for skill in common_skills]
    list_vec2 = [vector2.get(skill, 0.0) for skill in common_skills]

    dot_product = sum(a * b for a, b in zip(list_vec1, list_vec2))
    magnitude1 = math.sqrt(sum(val ** 2 for val in list_vec1))
    magnitude2 = math.sqrt(sum(val ** 2 for val in list_vec2))

    if magnitude1 * magnitude2 > 0:
        return dot_product / (magnitude1 * magnitude2)
    else:
        return 0.0


def main():
    # Placeholder for file creation as the environment doesn't have these files yet.
    # In a real scenario, these would be read from actual files.
    jobs_data = [
        {"id": "JD-1", "company": "Kakao", "role": "ML Engineer", "required": "Python, Machine Learning, Deep Learning, TensorFlow, PyTorch, SQL, Data Visualization", "preferred": "NLP, BERT, Feature Engineering, Statistics"},
        {"id": "JD-2", "company": "Naver", "role": "Backend Engineer", "required": "Java, Spring Boot, MySQL, PostgreSQL, Microservices, Docker, Kubernetes", "preferred": "REST API, CI/CD, Redis"},
        {"id": "JD-3", "company": "Line", "role": "Frontend Engineer", "required": "JavaScript, React, Vue, TypeScript, REST API, HTML/CSS", "preferred": "Node.js, GraphQL, Redux, Jest, AWS"}
    ]
    candidates_data = [
        {"id": "01", "name": "Arjun Sharma", "skills": "Pyhton, MachineLearning, SQL, pandas, numpy, Deep-learning", "background": "TCS Intern · BITS Pilani CSE 2024"},
        {"id": "02", "name": "Priya Nair", "skills": "JavaScrpit, Reacts, Node.JS, MongoDb, REST api, HTML/CSS", "background": "Freelance Web Developer · VIT IT 2024"},
        {"id": "03", "name": "Rahul Gupta", "skills": "Java, Spring Boot, MySql, Microservices, Docker, kubernates", "background": "Infosys SDE Intern · IIT Delhi 2023"},
        {"id": "04", "name": "Sneha Patel", "skills": "Python, TensorFlow, Keras, NLP, BERT, data-viz, matplotlib", "background": "IISc Research Assistant · IIIT Hyderabad AI 2024"},
        {"id": "05", "name": "Vikram Singh", "skills": "C++, Algoritms, Data Structure, competitive programming, python", "background": "Google SWE Intern · IIT Bombay 2024"},
        {"id": "06", "name": "Ananya Krishnan", "skills": "javascript, vue.js, python, flask, PostgreSQL, AWS, CI/CD", "background": "Full Stack Developer · NIT Trichy 2022"},
        {"id": "07", "name": "Karan Mehta", "skills": "Python, Sklearn, XGboost, feature engineering, SQL, tableau", "background": "Data Analyst · Delhi University 2023"},
        {"id": "08", "name": "Deepika Rao", "skills": "Java, Android, Kotlin, Firebase, REST, UI/UX, figma", "background": "Samsung Android Intern · NSIT 2024"},
        {"id": "09", "name": "Aditya Kumar", "skills": "Reactjs, TypeScrpit, GraphQL, redux, tailwind, nodejs, jest", "background": "Frontend SDE · Flipkart / IIIT Bangalore"},
        {"id": "10", "name": "Meera Iyer", "skills": "python, R, statistics, ML, regression, clustering, Power-BI", "background": "Data Science Intern · Wipro 2024"}
    ]

    # Write these to temporary CSV files so read_csv_file can pick them up.
    # This mimics the command-line usage structure.
    with open('jobs.csv', 'w', newline='') as f:
        fieldnames = ['id', 'company', 'role', 'required', 'preferred']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(jobs_data)

    with open('candidates.csv', 'w', newline='') as f:
        fieldnames = ['id', 'name', 'skills', 'background']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(candidates_data)


    jobs = read_csv_file('jobs.csv')
    candidates = read_csv_file('candidates.csv')

    # Step 1: Normalize candidate skills and create a map (id -> normalized_skills_list)
    normalized_candidate_skills_map = {c['id']: normalize_skills(c.get('skills', '')) for c in candidates}

    # Step 2: Build vocabulary from candidates only
    vocabulary = build_vocabulary(normalized_candidate_skills_map)

    num_candidates = len(candidates)

    # Step 3: Compute Document Frequency (DF) for skills in candidates
    document_frequency = compute_document_frequency(vocabulary, normalized_candidate_skills_map)

    # Step 4: Compute Inverse Document Frequency (IDF)
    idf = compute_idf(document_frequency, num_candidates)

    # Step 5: Build TF-IDF vectors for candidates
    candidate_tfidf_vectors = build_candidate_tfidf_vectors(normalized_candidate_skills_map, vocabulary, idf)

    # Step 6: Rank candidates
    ranked_results_with_names_and_scores = {}
    candidate_id_to_name = {c['id']: c['name'] for c in candidates}

    for job in jobs:
        job_raw_skills = job.get('required', '') + ', ' + job.get('preferred', '')
        job_normalized_skills = normalize_skills(job_raw_skills)

        # Build JD binary vector
        jd_vector = build_jd_binary_vector(vocabulary, job_normalized_skills)

        candidate_scores = {}
        for candidate_id, c_tfidf_vector in candidate_tfidf_vectors.items():
            score = cosine_similarity(jd_vector, c_tfidf_vector)
            candidate_scores[candidate_id] = score

        # Sort candidates by score (descending) and then by ID (ascending) for ties
        sorted_candidate_ids = sorted(candidate_scores, key=lambda x: (-candidate_scores[x], candidate_id_to_name.get(x, x)))

        top_3_candidates_with_scores = []
        for c_id in sorted_candidate_ids[:3]:
            score = candidate_scores[c_id]
            name = candidate_id_to_name.get(c_id, c_id)
            top_3_candidates_with_scores.append(f"{name}({score:.2f})")
        ranked_results_with_names_and_scores[job.get('id', '')] = top_3_candidates_with_scores

    # Print final output
    for job_id in ["JD-1", "JD-2", "JD-3"]:
        if job_id in ranked_results_with_names_and_scores:
            job_info = next((j for j in jobs if j['id'] == job_id), None)
            if job_info:
                print(f"{job_id} — {job_info['company']} ({job_info['role']})")
                print(", ".join(ranked_results_with_names_and_scores[job_id]))
                print()


if __name__ == '__main__':
    main()

